package cn.edu.nuist.lms.model;

import java.sql.Date;

public class Literature {
    private long id;
    private String author;
    private String title;
    private String category;
    private String publisher;
    private Date publishTime;
    private String volumeNumber;
    private String issueNumber;
    private long citedNumber;

    /** Generated by VSCode */

    public Literature() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public Date getPublishTime() {
        return publishTime;
    }

    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    public String getVolumeNumber() {
        return volumeNumber;
    }

    public void setVolumeNumber(String volumeNumber) {
        this.volumeNumber = volumeNumber;
    }

    public String getIssueNumber() {
        return issueNumber;
    }

    public void setIssueNumber(String issueNumber) {
        this.issueNumber = issueNumber;
    }

    public long getCitedNumber() {
        return citedNumber;
    }

    public void setCitedNumber(long citedNumber) {
        this.citedNumber = citedNumber;
    }

    @Override
    public String toString() {
        return "Literature [author=" + author + ", category=" + category + ", citedNumber=" + citedNumber + ", id=" + id
                + ", issueNumber=" + issueNumber + ", publishTime=" + publishTime + ", publisher=" + publisher
                + ", title=" + title + ", volumeNumber=" + volumeNumber + "]";
    }

}